"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:53:25.742320+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                      .option("header", "true")
                       .option("inferSchema", "false")
                       .load(input_path)
                      .withColumnRenamed("_c0", "transaction_id")
                      .withColumnRenamed("_c1", "merchant_id")
                      .withColumnRenamed("_c2", "amount")
                      .withColumnRenamed("_c3", "transaction_date")
                      .withColumnRenamed("_c4", "status")
                      .withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                    .option("inferSchema", "false")
                    .load(input_path.replace("transactions.csv", "merchants.csv"))
                   .withColumnRenamed("_c0", "merchant_id")
                   .withColumnRenamed("_c1", "merchant_name")
                   .withColumnRenamed("_c2", "category")
                   .withColumnRenamed("_c3", "city"))

    # Write transactions and merchants as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(os.path.join(output_path, "transactions"))
    merchants_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(os.path.join(output_path, "merchants"))

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .option("basePath", bronze_path)
                      .load(os.path.join(bronze_path, "ingestion_timestamp={}".format(run_date)))
                      .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                      .withColumn("amount", col("amount").cast(FloatType())))

    merchants_df = (spark.read.format("parquet")
                   .option("basePath", merchants_path)
                   .load(os.path.join(merchants_path, "ingestion_timestamp={}".format(run_date)))
                   .cache())

    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType())) \
                                      .withColumn("merchant_id", col("merchant_id").cast(StringType()))

    # Filter NULL transaction_id and negative amounts
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # Deduplicate on transaction_id keeping the latest ingestion_timestamp
    transactions_dedup_df = (transactions_df.groupBy("transaction_id")
                            .agg({"ingestion_timestamp": "max"})
                            .withColumnRenamed("max(ingestion_timestamp)", "ingestion_timestamp"))
    transactions_df = transactions_df.join(transactions_dedup_df, ["transaction_id", "ingestion_timestamp"], "inner")

    # Join with merchants (broadcast hint, cache merchants)
    transactions_enriched_df = (transactions_df.join(broadcast(merchants_df), transactions_df.merchant_id == merchants_df.merchant_id, "left_outer")
                                .withColumn("quality_flag", when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))

    # Write Silver Parquet partitioned by date
    transactions_enriched_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    # Define paths and run metadata
    input_path = "s3://your-bucket/input/"
    bronze_path = "s3://your-bucket/bronze/"
    silver_path = "s3://your-bucket/silver/"
    merchants_path = "s3://your-bucket/merchants/"
    run_date = "2026-05-27"
    run_id = "run_id_12345"

    # Ingest Bronze
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)

    # Transform Silver
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)

    # Write run metadata summary to a JSON file
    run_metadata = {"run_date": run_date, "run_id": run_id, "bronze_path": bronze_path, "silver_path": silver_path}
    with open("s3://your-bucket/metadata/run_metadata_{}.json".format(run_date), "w") as f:
        json.dump(run_metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, avg, first, last, mode, col
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType
import json

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate total revenue and transaction count per merchant
    merchant_performance_df = completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count")
        )
    
    # Calculate failure rate per merchant
    all_txns = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
            count("*").alias("total_txns")
        )
    failure_rate_df = all_txns.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join performance metrics with failure rates
    merchant_performance_df = merchant_performance_df.join(failure_rate_df["merchant_id", "date", "failure_rate_pct"], 
                                                            ["merchant_id", "date"], 
                                                            "left")
    
    # Write to output path
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate customer LTV metrics
    customer_ltv_df = completed_txns.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            first("transaction_date").alias("first_txn_date"),
            last("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    # Write to output path
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate total revenue and transaction count
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants")
        )
    
    # Calculate failure rate
    all_txns = silver_df.groupBy("date") \
       .agg(
            count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
            count("*").alias("total_txns")
        )
    failure_rate_df = all_txns.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join summary metrics with failure rates
    daily_summary_df = daily_summary_df.join(failure_rate_df["date", "failure_rate_pct"], "date", "left")
    
    # Write to output path
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths for each Gold table
    merchant_performance_output = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output = f"{gold_output_dir}/customer_ltv"
    daily_summary_output = f"{gold_output_dir}/daily_summary"
    
    # Run each Gold layer function
    build_merchant_performance(spark, silver_path, merchant_performance_output, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output)
    build_daily_summary(spark, silver_path, daily_summary_output, run_date)
    
    # Prepare run metadata summary
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables": [
            {"name": "merchant_performance", "path": merchant_performance_output},
            {"name": "customer_ltv", "path": customer_ltv_output},
            {"name": "daily_summary", "path": daily_summary_output}
        ]
    }
    
    # Write run metadata to JSON file
    with open(f"{gold_output_dir}/run_metadata.json", "w") as f:
        json.dump(run_metadata, f)

# Initialize Spark session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
