"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:49:53.254660+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max as spark_max, current_date, expr
from pyspark.sql.types import StructType, StructField, StringType, FloatType, TimestampType, IntegerType, DecimalType
import sys

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Define schema for Bronze layer
    bronze_schema = StructType([
        StructField("customer_id", StringType(), True),
        StructField("transaction_id", StringType(), True),
        StructField("transaction_date", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("payment_method", StringType(), True),
        StructField("status", StringType(), True),
        StructField("product_id", StringType(), True)
    ])
    
    # Read CSV data into DataFrame
    bronze_df = spark.read.csv(input_path, schema=bronze_schema, header=True)
    
    # Add metadata columns and partition by transaction_date
    bronze_df = bronze_df.withColumn("ingestion_timestamp", expr("current_timestamp()")) \
                          .withColumn("source_file_name", input_path) \
                          .withColumn("pipeline_run_id", lit(run_id)) \
                         .withColumn("transaction_date", to_timestamp(col("transaction_date"), "yyyy-MM-dd")) \
                         .withColumn("transaction_date", expr("date_format(transaction_date, 'yyyy-MM-dd')"))
    
    # Write DataFrame to Bronze layer partitioned by transaction_date
    bronze_df.write.partitionBy("transaction_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze layer with partition pruning
    bronze_df = spark.read.parquet(bronze_path).where(col("transaction_date") == run_date)
    
    # Define schema for Silver layer
    silver_schema = StructType([
        StructField("customer_id", StringType(), True),
        StructField("transaction_id", StringType(), True),
        StructField("transaction_date", TimestampType(), True),
        StructField("amount", FloatType(), True),
        StructField("payment_method", StringType(), True),
        StructField("status", StringType(), True),
        StructField("product_id", StringType(), True),
        StructField("ingestion_timestamp", TimestampType(), True),
        StructField("source_file_name", StringType(), True),
        StructField("pipeline_run_id", StringType(), True)
    ])
    
    # Cast columns to correct types
    silver_df = bronze_df.select([col(c.name).cast(c.dataType) for c in silver_schema])
    
    # Filter NULL transaction_id and negative amounts
    silver_df = silver_df.filter(col("transaction_id").isNotNull() & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    silver_df = silver_df.withColumn("rank", expr("row_number() over (partition by transaction_id order by ingestion_timestamp desc)")) \
                         .filter(col("rank") == 1).drop("rank")
    
    # Read merchants data and apply broadcast hint
    merchants_df = spark.read.parquet(merchants_path).hint("broadcast")
    
    # Join with merchants on merchant_id
    silver_df = silver_df.join(merchants_df, silver_df.product_id == merchants_df.merchant_id, "left")
    
    # Add quality_flag column
    null_customer_id_count = silver_df.filter(col("customer_id").isNull()).count()
    total_rows = silver_df.count()
    quality_halt_threshold = 0.05
    quality_flag = "CLEAN" if (null_customer_id_count / total_rows) <= quality_halt_threshold else "UNMATCHED"
    
    silver_df = silver_df.withColumn("quality_flag", lit(quality_flag))
    
    # Write DataFrame to Silver layer partitioned by transaction_date
    silver_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = SparkSession.builder.appName("ChurnRiskPipeline").getOrCreate()
    
    # Define paths and run details
    input_path = "s3://path/to/bronze/data"
    bronze_output_path = "s3://path/to/silver/data/bronze"
    merchants_path = "s3://path/to/merchants/data"
    silver_output_path = "s3://path/to/silver/data/silver"
    gold_output_path = "s3://path/to/gold/data"
    run_date = "2023-10-01"
    run_id = "run_id_12345"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_output_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, bronze_output_path, merchants_path, silver_output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max, sum, count, expr, collect_set, first, lit, broadcast
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType, DateType
import json

def run_gold(spark, silver_path, gold_output_dir, run_date):
    run_metadata = {}
    
    try:
        build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
        build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
        build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
        
        run_metadata['status'] = 'SUCCESS'
        run_metadata['run_date'] = run_date
    except Exception as e:
        run_metadata['status'] = 'FAILURE'
        run_metadata['error'] = str(e)
    
    with open(f"{gold_output_dir}/run_metadata_{run_date}.json", 'w') as f:
        json.dump(run_metadata, f)

def build_merchant_performance(spark, silver_path, output_path, run_date):
    silver_df = spark.read.parquet(silver_path)
    
    merchant_performance_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("merchant_id", "merchant_name", "category", "city", "transaction_date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    merchant_performance_df \
       .repartition("transaction_date") \
       .write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    silver_df = spark.read.parquet(silver_path)
    
    customer_ltv_df = silver_df.filter(col("status") == "COMPLETED") \
       .groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            expr("first(transaction_date)").alias("first_txn_date"),
            expr("max(transaction_date)").alias("last_txn_date"),
            first(collect_set("payment_method").over(Window.partitionBy("customer_id").orderBy(col("total_spent").desc()))).alias("preferred_payment_method")
        )
    
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    silver_df = spark.read.parquet(silver_path)
    
    daily_summary_df = silver_df.filter(col("transaction_date") >= expr(f"current_date() - interval 30 days")) \
        .groupBy("transaction_date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id")).alias("unique_customers"),
            count(col("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    daily_summary_df \
       .repartition("transaction_date") \
       .write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

if __name__ == "__main__":
    spark = SparkSession.builder.appName("Churn Risk Gold Pipeline").getOrCreate()
    silver_path = "path_to_silver_layer"
    gold_output_dir = "path_to_gold_output"
    run_date = "2023-10-01"
    
    run_gold(spark, silver_path, gold_output_dir, run_date)
